SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE IF NOT EXISTS "TB_NEEDLE"
(
    "ID_NEEDLE"    BIGSERIAL,
    "UUID"         VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "DESCRIPTION"  VARCHAR(150)        NOT NULL,
    "DT_INCLUSION" TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID_NEEDLE")

);




