SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "TB_APPLICATION_LOCATION"
(
    "ID_APPLICATION_LOCATION" BIGSERIAL,
    "UUID"                    VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "DESCRIPTION"             VARCHAR(150)        NOT NULL,
    "DT_INCLUSION"            TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID_APPLICATION_LOCATION")

);


