SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "TB_BASIC_VACCINATION"
(
    "ID_BASIC_VACCINATION" BIGSERIAL,
    "UUID"                 VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "DESCRIPTION"          VARCHAR(150)        NOT NULL,
    "DT_INCLUSION"         TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID_BASIC_VACCINATION")

);

