SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "TB_RECOMMENDED_AGE"
(
    "ID_RECOMMENDED_AGE" BIGSERIAL,
    "RECOMMENDED_AGE"    INTEGER            NOT NULL,
    "UUID"               VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "DESCRIPTION"        VARCHAR(150)        NOT NULL,
    "DT_INCLUSION"       TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY ("ID_RECOMMENDED_AGE")

);
