SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "TB_DOSAGE"
(
    "ID_DOSAGE"    BIGSERIAL,
    "UUID"         VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "ID_RECOMMENDED_AGE"      BIGSERIAL NOT NULL ,
    "ID_REINFORCEMENT"        BIGSERIAL NOT NULL ,
    "DESCRIPTION"  VARCHAR(150)        NOT NULL,
    "DT_INCLUSION" TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    FOREIGN KEY ("ID_RECOMMENDED_AGE") REFERENCES "TB_RECOMMENDED_AGE" ("ID_RECOMMENDED_AGE"),
    FOREIGN KEY ("ID_REINFORCEMENT") REFERENCES "TB_REINFORCEMENT" ("ID_REINFORCEMENT"),
    PRIMARY KEY ("ID_DOSAGE")

);



