SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


CREATE TABLE IF NOT EXISTS "TB_VACCINE"
(
    "ID_VACCINE"              BIGSERIAL,
    "UUID"                    VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "DESCRIPTION"             VARCHAR(150)        NOT NULL,
    "NAME"                    VARCHAR(150)        NOT NULL,
    "DT_INCLUSION"            TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    "ID_APPLICATION_LOCATION" BIGSERIAL,
    "ID_BASIC_VACCINATION"    BIGSERIAL,
    "ID_COMPOSITION"          BIGSERIAL,
    "ID_DISEASE"              BIGSERIAL,
    "ID_NEEDLE"               BIGSERIAL,
    "ID_ROUTE_ADMINISTRATION" BIGSERIAL,
    "ID_SIDE_EFFECT"          BIGSERIAL,
    "ID_VALIDITY_AFTER_OPEN"  BIGSERIAL,
    FOREIGN KEY ("ID_APPLICATION_LOCATION") REFERENCES "TB_APPLICATION_LOCATION" ("ID_APPLICATION_LOCATION"),
    FOREIGN KEY ("ID_BASIC_VACCINATION") REFERENCES "TB_BASIC_VACCINATION" ("ID_BASIC_VACCINATION"),
    FOREIGN KEY ("ID_COMPOSITION") REFERENCES "TB_COMPOSITION" ("ID_COMPOSITION"),
    FOREIGN KEY ("ID_DISEASE") REFERENCES "TB_DISEASE" ("ID_DISEASE"),
    FOREIGN KEY ("ID_NEEDLE") REFERENCES "TB_NEEDLE" ("ID_NEEDLE"),
    FOREIGN KEY ("ID_ROUTE_ADMINISTRATION") REFERENCES "TB_ROUTE_ADMINISTRATION" ("ID_ROUTE_ADMINISTRATION"),
    FOREIGN KEY ("ID_SIDE_EFFECT") REFERENCES "TB_SIDE_EFFECT" ("ID_SIDE_EFFECT"),
    FOREIGN KEY ("ID_VALIDITY_AFTER_OPEN") REFERENCES "TB_VALIDITY_AFTER_OPEN" ("ID_VALIDITY_AFTER_OPEN"),
    PRIMARY KEY ("ID_VACCINE")
);
