SET search_path TO "DBVACCINE";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "TB_VACCINE_DOSAGE"
(
    "ID_VACCINE_DOSAGE" BIGSERIAL,
    "UUID"              VARCHAR(50) UNIQUE NOT NULL DEFAULT uuid_generate_v4(),
    "ID_VACCINE"        BIGSERIAL          NOT NULL,
    "ID_DOSAGE"         BIGSERIAL          NOT NULL,
    "DT_INCLUSION"      TIMESTAMP          NOT NULL default CURRENT_TIMESTAMP,
    FOREIGN KEY ("ID_VACCINE") REFERENCES "TB_VACCINE" ("ID_VACCINE"),
    FOREIGN KEY ("ID_DOSAGE") REFERENCES "TB_DOSAGE" ("ID_DOSAGE"),
    PRIMARY KEY ("ID_VACCINE_DOSAGE")

);
